spring:
   application: 
    name: okex-trade-server
   datasource:
        name: okexdb
        #url: jdbc:mysql://ifredev.mysqldb.chinacloudapi.cn:3306/ifrehx?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        #username: ifredev%hx
        #password: ifreDIje0382
        #url: jdbc:mysql://47.106.84.51:3306/okextrande?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
        url: jdbc:mysql://localhost:3306/okextrande?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
        username: root
        password: Ja5668!@
        #使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 100
        initialSize: 5
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  
mybatis:
  mapper-locations: classpath:mapper/com/okex/mybatis/*.xml
  type-aliases-package: com.okex.mybatis.dao

mapper:
  mappers:  com.okex.mybatis.dao
  not-empty: false
  identity: MYSQL

pagehelper: 
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

mail: 
  host: smtp.exmail.qq.com
  fromUser: 
  password: 
  toUser: 
  copyTo: 
  timeout: 2500
  auth: true

